[google_sheets]
URL_DASHBOARD = "https://docs.google.com/spreadsheets/d/1xSAMQ0fCps5BcqSJKyKEeQ-9XJChsRQj43PVlarnQ6I/export?format=csv&gid=40883231"
URL_ACCOUNT = "https://docs.google.com/spreadsheets/d/1xSAMQ0fCps5BcqSJKyKEeQ-9XJChsRQj43PVlarnQ6I/export?format=csv&gid=2038053740"
URL_CALENDAR = "https://docs.google.com/spreadsheets/d/1xSAMQ0fCps5BcqSJKyKEeQ-9XJChsRQj43PVlarnQ6I/export?format=csv&gid=712389288"
URL_RECORDS = "https://docs.google.com/spreadsheets/d/1xSAMQ0fCps5BcqSJKyKEeQ-9XJChsRQj43PVlarnQ6I/export?format=csv&gid=1476127016"
URL_PNL_DAILY = "https://docs.google.com/spreadsheets/d/1xSAMQ0fCps5BcqSJKyKEeQ-9XJChsRQj43PVlarnQ6I/export?format=csv&gid=1294893673"
URL_PNL_MONTHLY = "https://docs.google.com/spreadsheets/d/1xSAMQ0fCps5BcqSJKyKEeQ-9XJChsRQj43PVlarnQ6I/export?format=csv&gid=660557594"
